version: '3.7'

services:
  springboot:
    image: madhurinaidu/spring101:1.0
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/crudwithspringpro/"]
      interval: 30s
      timeout: 5s
      retries: 3

  mysql:
    container_name: localhost
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root  # Only the root user password
      - MYSQL_DATABASE=demo  # Optional: Create a database on startup
      # Optionally create a regular user (not root):
      # - MYSQL_USER=myuser
      # - MYSQL_PASSWORD=mypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-proot"]
      interval: 30s
      timeout: 5s
      retries: 3
