version: '3.7'

services:
  springboot:
    image: madhurinaidu/l1:1.0
    ports:
      - "8080:8080"
    depends_on:
      - mysql  # Just use the service name without conditions here
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://db:8080/crudwithspringpro"]  # Adjust if needed
      interval: 30s
      timeout: 5s
      retries: 3

  mysql:
    container_name: db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-proot"]
      interval: 30s
      timeout: 5s
      retries: 3
