version: '3.7'

services:
  springboot:
    image: madhurinaidu/spring100:1.0
    ports:
      - "8080:8080"
    depends_on:
      mysql:  # Change to just the service name
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/crudwithspringpro/"]
      interval: 30s
      timeout: 5s
      retries: 3

  mysql:
    container_name: db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=demo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 5s
      retries: 3
